.TH collatzGraph 1 "Sunday, Febuary 18, 2018" "alpha" "USER COMMANDS"

.SH NAME
collatzGraph \- graphs out collatz sequences in the terminal
.SH SYNOPSIS
.B collatzGraph 
[gbf|gbs]
.SH DESCRIPTION 
The collatz graph program has two modes of operation, gbf and gbs. Gbf is graph by the first element to the last, and gbs is graph by size of the elements(largest first). 

When you run the program, it will ask you for a number to collatz.

The collatz function is a function that takes a number, and multiplies it by three, then adds one if it is odd, but if the number is even, it divides it by two. This function always returns 1, but nobody can prove it is true.
